// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtgqI5TjVptdE1ww4K9Hg851KGRai-RVM',
    appId: '1:770241729737:web:ee37638e0c41278884a918',
    messagingSenderId: '770241729737',
    projectId: 'fotofocus-57198',
    authDomain: 'fotofocus-57198.firebaseapp.com',
    storageBucket: 'fotofocus-57198.firebasestorage.app',
    measurementId: 'G-E6NQKXBGXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHJoEv9DShs9Ka7FvNa44_MYNZyBYFrlI',
    appId: '1:770241729737:android:276093fbdc37080384a918',
    messagingSenderId: '770241729737',
    projectId: 'fotofocus-57198',
    storageBucket: 'fotofocus-57198.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsj8umXaN2c99bXUyADOPsGnAKZH0dFGg',
    appId: '1:770241729737:ios:18bbcd445457fa1384a918',
    messagingSenderId: '770241729737',
    projectId: 'fotofocus-57198',
    storageBucket: 'fotofocus-57198.firebasestorage.app',
    iosBundleId: 'com.example.fotofocus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsj8umXaN2c99bXUyADOPsGnAKZH0dFGg',
    appId: '1:770241729737:ios:18bbcd445457fa1384a918',
    messagingSenderId: '770241729737',
    projectId: 'fotofocus-57198',
    storageBucket: 'fotofocus-57198.firebasestorage.app',
    iosBundleId: 'com.example.fotofocus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtgqI5TjVptdE1ww4K9Hg851KGRai-RVM',
    appId: '1:770241729737:web:f6c95c9d0539432584a918',
    messagingSenderId: '770241729737',
    projectId: 'fotofocus-57198',
    authDomain: 'fotofocus-57198.firebaseapp.com',
    storageBucket: 'fotofocus-57198.firebasestorage.app',
    measurementId: 'G-WDHMBD0XD6',
  );

}